php artisan make:model Model\Referensi\Bank
php artisan make:model Model\Referensi\RekeningBank
php artisan make:model Model\Referensi\Quotes
php artisan make:model Model\Referensi\Ticker
php artisan make:model Model\Referensi\Ruangan
php artisan make:model Model\Referensi\Imam
php artisan make:model Model\Referensi\SettingBooking
php artisan make:model Model\Referensi\Agenda
php artisan make:model Model\Referensi\AgendaDetail
php artisan make:model Model\Referensi\TypeInfaq
php artisan make:model Model\Transaksi\Infaq
php artisan make:model Model\Referensi\Inventaris
php artisan make:model Model\Referensi\JenisInventaris
php artisan make:model Model\Referensi\Alumni
php artisan make:model Model\Referensi\Divisi
php artisan make:model Model\Referensi\Jabatan
php artisan make:model Model\Referensi\Pegawai
php artisan make:model Model\Referensi\PegawaiDetail
php artisan make:model Model\Referensi\Siswa
php artisan make:model Model\Referensi\JenisKegiatan

php artisan make:controller Referensi\BankController
php artisan make:controller Referensi\RekeningBankController
php artisan make:controller Referensi\QuotesController
php artisan make:controller Referensi\TickerController
php artisan make:controller Referensi\RuanganController
php artisan make:controller Referensi\ImamController
php artisan make:controller Referensi\SettingBookingController
php artisan make:controller Referensi\AgendaController
php artisan make:controller Referensi\AgendaDetailController
php artisan make:controller Referensi\TypeInfaqController
php artisan make:controller Transaksi\InfaqController
php artisan make:controller Referensi\InventarisController
php artisan make:controller Referensi\JenisInventarisController
php artisan make:controller Referensi\AlumniController
php artisan make:controller Referensi\DivisiController
php artisan make:controller Referensi\JabatanController
php artisan make:controller Referensi\PegawaiController
php artisan make:controller Referensi\PegawaiDetailController
php artisan make:controller Referensi\SiswaController
php artisan make:controller Referensi\JenisKegiatan

php artisan make:request Referensi\StoreBank
php artisan make:request Referensi\StoreRekeningBank
php artisan make:request Referensi\StoreQuotes
php artisan make:request Referensi\StoreTicker
php artisan make:request Referensi\StoreRuangan
php artisan make:request Referensi\StoreImam
php artisan make:request Referensi\StoreSettingBooking
php artisan make:request Referensi\StoreAgenda
php artisan make:request Referensi\StoreAgendaDetail
php artisan make:request Referensi\StoreTypeInfaq
php artisan make:request Transaksi\StoreInfaq
php artisan make:request Referensi\StoreInventaris
php artisan make:request Referensi\StoreJenisInventaris
php artisan make:request Referensi\StoreAlumni
php artisan make:request Referensi\StoreDivisi
php artisan make:request Referensi\StoreJabatan
php artisan make:request Referensi\StorePegawai
php artisan make:request Referensi\StorePegawaiDetail
php artisan make:request Referensi\StoreSiswa
php artisan make:request Referensi\StoreJen
